source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
pod 'GoogleMaps'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
pod 'AFNetworking', '~> 3.0'
#source 'https://github.com/SwiftyJSON/SwiftyJSON.git'
#platform :ios, '8.0'
#use_frameworks!
#pod 'SwiftyJSON', '~> 2.3.2'

platform :ios, '8.0'
use_frameworks!

target 'SuperTopSecretProj' do
      pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end
